[
    {
    "Rname": "Slow roast ras el hanout lamb & couscous",
    "Rpeparation_time":"40 mins",
    "Rcook_time":"4 hours plus at least 1 hr marinating",
   
    "Rserves":4,
    "Ringredients":["5 garlic cloves","1 lemon, juiced","6 tbsp ras el hanout spice mix (shop-bought or see tip, below)","2 tbsp olive oil","small shoulder of lamb (about 2kg)","2 red onions, cut into large wedges","400g couscous","100g raisins","400g can chickpeas drained","small bunch of parsley chopped","small bunch of coriander chopped","1 preserved lemon finely chopped or the juice of ½ lemon"],
    "Rmethodecook": ["Using a pestle and mortar or a mini chopper, mash or chop the garlic with a generous pinch of salt, then add the lemon juice, ras el hanout spice mix and olive oil, then pound or chop to a rough paste. Use a small knife to make small incisions all over the lamb. Sit the lamb in a large, shallow casserole dish or deep roasting tin, then rub the paste all over the lamb and into the cuts. Leave at room temperature for 1 hr, or better still cover and chill overnight.","When ready to cook, heat the oven to 160C/140C fan/gas 3. Scatter the onion wedges around the lamb, then cover the dish with a lid or tightly with foil and roast for 3 hrs. Remove from the oven and uncover. Stir the onions and baste the lamb in the juices, then turn the oven up to 180C/160C fan/gas 4 and continue to roast the lamb, uncovered, for 25-30 mins until browned.","When ready to cook, heat the oven to 160C/140C fan/gas 3. Scatter the onion wedges around the lamb, then cover the dish with a lid or tightly with foil and roast for 3 hrs. Remove from the oven and uncover. Stir the onions and baste the lamb in the juices, then turn the oven up to 180C/160C fan/gas 4 and continue to roast the lamb, uncovered, for 25-30 mins until browned.","Lift the lamb and onions onto a board to rest and put the kettle on. Stir the couscous and raisins into the lamb dish so they’re coated in the roasting juices. Pour over enough boiling water from the kettle to just cover the couscous, then cover the dish and leave for 5 mins. Uncover and fluff the couscous up with a wooden spoon, then stir through the chickpeas, chopped herbs and preserved lemon or lemon juice, and season to taste. Bring the lamb, onions and the couscous to the table to serve."],
    "Rimage":"https://res.cloudinary.com/dnwi9wvci/image/upload/v1670602461/mawi/slow-roast-ras-el-hanout-lamb-a7a8445_bjdljs.jpg",
    "Rlike": 0,
    "Rdislike":0,
    "Rcategorie":"dinner"
},
    {
    "Rname": "Giant couscous & tomato salad with zhoug-style dressing",
    "Rpeparation_time":"5 mins",
    "Rcook_time":"15 mins plus cooling",
    "Rserves":4,
    "Ringredients":["4 large vine tomatoes, diced","½ red onion, finely chopped","150g giant couscous or fregola","½ small bunch of coriander, roughly chopped","handful of parsley leaves, roughly chopped","1 lemon, juiced","2 green chillies, chopped","1 garlic clove, roughly chopped","½ tsp ground cumin","½ tsp caster sugar","3 tbsp olive oil"],
    "Rmethodecook": ["Put the tomatoes and onion in a large bowl with ½ tsp sea salt. Toss and leave to sit.","Cook the couscous in a pan of boiling salted water for 8-10 mins until tender (don’t overcook it – you want it a bit under so it can soak up the juices from the tomato), then drain really well. Cool for 10 mins then toss with the tomato and onion mixture.","Blend all the dressing ingredients with 1 tbsp water and ½ tsp sea salt until smooth. Drizzle some over the couscous, then serve the rest on the side for people to help themselves."],
    "Rimage":"https://res.cloudinary.com/dnwi9wvci/image/upload/v1670602940/mawi/Giant-couscous-and-tomato-salad-with-zhoug-style-dressing-62c81db_eaqj3j.jpg",
    "Rlike": 0,
    "Rdislike":0,
    "Rcategorie":"dessert"
},

    {
    "Rname": "PASTA BAKE WITH SAUSAGE ",
    "Rpeparation_time":"10 mins",
    "Rcook_time":"50 minutes",
    "Rserves":8,
    "Ringredients":["1 lb.(454 grams) penne pasta","2 tablespoons olive oil",
    "1 lb. Italian sausage",
    "1 cup onion, finely chopped",
    "1 tablespoon garlic, minced",
    "4 cups tomato sauce",
    "1 tablespoon Italian seasoning" ,
    "1 cup Parmesan cheese, freshly grated, divided",
    "¼ cup fresh parsley, finely chopped",
    "¼ cup fresh basil, chopped",
    "1 teaspoon salt (or to taste)",
    "½ teaspoon ground black pepper (or to taste)",
    "3 cups fresh mozzarella cheese, shredded"],
    "Rmethodecook": ["Preheat oven to 375F.","Bring a large pot of salted water to a boil over medium-high heat. Add pasta and cook until al dente (fully cooked but still firm), about 8-10 minutes, or according to package directions. Drain well and set aside.","Meanwhile, heat olive oil in a large pot (or 4 qt. Dutch oven) for 2 minutes over medium-high heat until the hot oil sizzles. Add sausage and stir to cook until browned, about 5-7 minutes. Use a spatula to break the sausages into small pieces.","Add onions and garlic and sauté until soft and tender, about 2-3 minutes. Stir to combine.","Pour in tomato sauce, turn the heat down to medium, and bring the meat sauce to a simmer, stirring occasionally. Stir in Italian seasoning, ½ cup Parmesan cheese, parsley and basil. Season with salt and pepper.","Turn the heat down to low and simmer for 5-7 minutes, stirring occasionally. Simmering helps develop richer flavour in the sauce.","Transfer the cooked and drained pasta into the sauce and toss well to mix evenly.","Spread half of the pasta into a 9x13 casserole pan and top with half of mozzarella cheese (1.5 cups). Add the remaining pasta and sprinkle the remaining mozzarella and Parmesan cheese evenly on top.","Bake the pasta for 25 minutes until the melted cheese is golden brown. Let cool for 15 minutes, then serve."],
    "Rimage":"https://res.cloudinary.com/dnwi9wvci/image/upload/v1670604833/mawi/pasta-bake-with-sausage-baked-ziti-5_gxvwyj.jpg",
    "Rlike": 0,
    "Rdislike":0,
    "Rcategorie":"dinner"
},

    {
    "Rname": "CHICKEN PENNE PASTA",
    "Rpeparation_time":"10 mins",
    "Rcook_time":"25 mins",
    "Rserves":4,
    "Ringredients":["2 boneless and skinless chicken breasts (about 1 pound)","½ teaspoon salt","¼ teaspoon ground black pepper","1 tablespoon vegetable oil","½ pound penne pasta (2 cups)","2 tablespoons butter","2 tablespoons garlic, minced","1 tablespoon all-purpose flour","1 cup heavy cream","½ cup chicken broth (or reserved hot pasta water)","¼ cup Parmesan cheese, freshly grated","¼ teaspoon salt (or to taste)","¼ teaspoon ground black pepper (or to taste)","1 teaspoon fresh parsley (optional, for garnish)"],
    "Rmethodecook": ["Bring a large pot of salted water to a boil over medium-high heat. Add penne pasta and cook until al dente according to package directions, about 8-10 minutes. Reserve ½ cup of the hot pasta water in a bowl (if using instead of chicken stock). Drain the pasta and set aside.","Use a paper towel to pat the chicken breasts completely dry. Season with salt and pepper.","In a large skillet, heat oil over medium-high heat until the hot oil sizzles, about 1-2 minutes. Add chicken and sear until golden brown, 6-8 minutes per side. Slice the chicken into ½-inch strips, transfer onto a plate, and cover with aluminium foil to stay moist.","In the same skillet, add butter and garlic and sauté until fragrant, about 1 minute. Add flour and cook until thickened into a paste, about 1 minute.","Add heavy cream, chicken broth (or reserved hot pasta water),  and Parmesan cheese. Bring the sauce to a simmer over medium heat and simmer for 2-3 minutes until thickened to a desired consistency, stirring occasionally. Season with salt and pepper to taste.","Add the chicken and pasta to the skillet and toss well to coat. Garnish with parsley and serve immediately."],
    "Rimage":"https://res.cloudinary.com/dnwi9wvci/image/upload/v1670605247/mawi/chicken-penne-pasta-768x1152_kp6ppw.jpg",
    "Rlike": 0,
    "Rdislike":0,
    "Rcategorie":"dinner"
},

    {
    "Rname": "Sweetcorn custard tart",
    "Rpeparation_time":"20 mins",
    "Rcook_time":"1 hour",
    "Rserves":6,
    "Ringredients":["200g plain flour, plus extra for dusting","50g fine cornmeal","125g cold unsalted butter, cut into cubes, plus extra for the tin","1 tbsp caster sugar","500g sweetcorn (defrosted if frozen)","150g unsalted butter","75g caster sugar, plus 3 tbsp","300ml whole milk","6 egg yolks (freeze the whites for another recipe)","1 tsp vanilla extract","200g crème fraîche plus extra to serve (optional)","nutmeg, for grating"],
    "Rmethodecook": ["Tip the flour, cornmeal, butter, sugar and 1 tsp salt into a large bowl and rub together until the mixture resembles breadcrumbs. Add 50-100ml water, a little at a time, until a dough forms.",
    "Butter a loose-bottomed 23cm tart tin. Roll the pastry out on a lightly floured surface until it’s just larger than the diameter of the tin and around 2mm thick. Loosely drape the pastry over the rolling pin and unravel into the tin. Carefully push the pastry into the base and up the side. Use a fork to prick the base all over, then chill for 30 mins.",
    "Heat the oven to 180C/160C fan/ gas 4. Scrunch up a sheet of baking parchment and use it to line the pastry case, then fill with baking beans or uncooked rice, gently pushing these down. Bake for 15 mins, then remove the beans and parchment and bake for 10 mins more until lightly golden. Remove from the oven and leave to cool.",
    "While the pastry case is baking, make the custard. Tip the sweetcorn into a heavy-based, wide pan and cook over a medium-high heat for 6 mins until the corn smells toasted. Add the butter and reduce the heat to medium. After about 5 mins, or when the butter starts to smell nutty, add the 3 tbsp of sugar and continue to stir. After a couple more minutes, stir in the milk and turn off the heat. Set aside to cool slightly. Whisk the egg yolks along with the remaining 75g sugar in a medium bowl until the mixture is pale, yellow and creamy.",
    "Transfer the corn mixture to a food processor and blitz until smooth. Push through a sieve into a large bowl and discard the fibrous outer kernels caught in the sieve. (You may need to do this in two batches.)",
    "While the sweetcorn mixture is still hot, slowly add it to the egg yolk mixture, whisking continuously as you do. Stir in the vanilla and crème fraîche until just combined – be careful not to over-mix, as air bubbles may form on the surface.",
    "Pour the custard into the cooled pastry case, then bake for 25-35 mins until the mixture is set with a slight wobble in the middle. Generously grate over some nutmeg, then leave to cool completely before slicing. Serve with extra crème fraîche, if you like."],
    "Rimage":"https://res.cloudinary.com/dnwi9wvci/image/upload/v1670605542/mawi/Sweetcorn-custard-tart-41ad495_mchzu3.jpg",
    "Rlike": 0,
    "Rdislike":0,
    "Rcategorie":"breakfast"
},

    {
    "Rname": "Custard buns",
    "Rpeparation_time":"1 hrs 30 mins",
    "Rcook_time":"20 mins plus overnight proving and 1 hr cooling",
    "Rserves":8,
    "Ringredients":["300g strong white flour, plus 1 tsp and extra for dusting",
    "175ml double cream",
    "45g caster sugar, plus 1 tsp",
    "2 tsp fast-action dried yeast",
    "1 egg plus 3 egg yolks and 1 egg white, at room temperature (freeze the extra whites to use in another recipe)",
    "vegetable oil, for proving",
    "1 tbsp whole milk",
    "fresh or roasted fruit (such as plums or rhubarb), to serve (optional)",
    "15g plain flour",
    "15g icing sugar", 
    "15g cold unsalted butter",
    "60g caster sugar",
    "15g cornflour",
    "1 egg",
    "90ml whole milk",
    "160ml double cream",
    "1⁄2 tsp vanilla bean paste"
   ],
    "Rmethodecook": ["Tip 35g of the flour and the cream into a pan and whisk over a low heat for 1-2 mins until smooth. Pour into a heatproof bowl and set aside to cool. Meanwhile, mix 1 tsp sugar, 1 tsp flour and the yeast with 1 tbsp warm water. Cover. Leave for 15 mins until bubbling.",
    "Tip the egg and egg yolks into a large bowl or stand mixer with the 45g sugar. Beat for 4-5 mins until pale and fluffy. Reduce the speed to low, add 1/4 tsp salt and the cream mixture, and beat to combine. Add the yeast mixture and sift in the remaining 265g flour, then mix on a low speed for 10 mins using the dough hook attachment. Or, knead by hand for 5 mins, rotating the bowl as you do. Cover and leave to prove in a warm place for 20 mins. Knead again for 3-5 mins until the dough is stretchy, then transfer to a lightly oiled bowl, cover and leave at room temperature for another 20 mins. Transfer to the fridge to prove for about 8-12 hrs, or until doubled in size.",
    "For the streusel, mix the flour with the sugar and a pinch of salt, then rub in the butter until the mixture resembles fine breadcrumbs. Keep in the the freezer until ready to use.",
    "For the custard, whisk the sugar, cornflour and ¼ tsp salt together in a small bowl. Add the egg and whisk to combine, then whisk in the milk and set aside. Bring the cream and vanilla to the boil in a saucepan. Remove from the heat and add the egg mixture slowly, whisking continuously. Cook over a low-medium heat for 7-10 mins, whisking all the time, until smooth and thick. Remove from the heat, cover and leave to cool for 30 mins",
    "Roll the dough out on a lightly floured surface until 2cm thick. Stamp out eight 6cm circles and use a tablespoon to press a dip into the middle of each. Using your hands, stretch each circle to about 8cm, keeping a raised border. Arrange on a large baking tray lined with baking parchment and fill each dip with 1 tbsp of the custard. Heat the oven to 180C/160C fan/gas 4.",
    "Leave to prove in a warm place for 30 mins until they slowly spring back when gently pressed. Mix the egg white with 1 tbsp milk and a pinch of salt and brush this over the sides of the buns. Sprinkle with the frozen streusel.",
    "Bake for 10 mins, then reduce the oven to 160C/140C fan/gas 3 and bake for another 8-10 mins. Leave to cool for 30 mins, then serve with fresh or roasted fruit, if you like. Will keep chilled for up to two days. Serve at room temperature."],
    "Rimage":"https://res.cloudinary.com/dnwi9wvci/image/upload/v1670605999/mawi/Custard-buns-1c17677_mvases.jpg",
    "Rlike": 0,
    "Rdislike":0,
    "Rcategorie":"breakfast"
},

    {
    "Rname": "Royal summer trifle",
    "Rpeparation_time":"25 mins",
    "Rcook_time":"20 mins plus several hours chilling",
    "Rserves":10,
    "Ringredients":["500ml fresh shop-bought vanilla custard",
    "400g madeira cake, cut into chunks",
    "70ml berry cordial of your choice",
    "150g raspberries",
    "300ml double cream",
    "3 tbsp icing sugar",
    "1 tsp vanilla bean paste",
    "250g strawberries",
    "small handful of mint leaves, to garnish",
    "1 orange, halved and sliced",
    "6 gelatine leaves",
    "100g caster sugar",
    "1 lemon, zest pared into strips, juiced",
    "500g strawberries, hulled",
    "a drop of red food colouring (optional)",
    "600ml double cream",
    "200ml caster sugar",
    "2 oranges, zested and juiced"],
    "Rmethodecook": ["First, make the jelly. Put the gelatine in a small bowl, cover with water and set aside to soak. Meanwhile, tip the sugar, lemon zest and juice and 400ml water into a pan over a low heat and simmer, stirring occasionally until the sugar has dissolved. Add the strawberries and bring to the boil, then reduce the heat to a simmer and cook for 5 mins until the strawberries have broken down. Pour the mixture through a sieve into a jug. Squeeze the excess water from the gelatine and stir this through the strawberry mixture until dissolved, then stir in a drop of red food colouring, if using. ",
    "Pour the custard into the base of a 3-litre trifle bowl and top with the cake pieces. Drizzle with the berry cordial and scatter with the raspberries. Slowly and carefully pour over the jelly mixture and chill for 5 hrs until set.",
    "When the jelly layer is set, make the orange cream layer. Put the cream, sugar and orange zest in a pan over a low heat and bring to a simmer. Turn up the heat to medium and bubble for 3 mins exactly, then immediately remove from the heat and stir in the orange juice. Pour the mixture through a sieve over the set jelly layer and chill for 4 hrs.",
    "Whip the double cream, icing sugar and vanilla bean paste to soft peaks using an electric whisk, then dollop the whipped cream over the trifle using a large spoon. Chill for at least 1 hr or until ready to serve. Halve most of the strawberries through the stem and scatter these over the trifle along with the mint leaves. Serve the orange slices and remaining whole strawberries in a bowl on the side."],
    "Rimage":"https://res.cloudinary.com/dnwi9wvci/image/upload/v1670606593/mawi/20220324_goodfood2252-d6595a0_wbi8mi.jpg",
    "Rlike": 0,
    "Rdislike":0,
    "Rcategorie":"dessert"
},

    {
    "Rname": "Spicy beef taco bowl",
    "Rpeparation_time":"15 mins",
    "Rcook_time":"25 mins",
    "Rserves":4,
    "Ringredients":["1 tsp olive oil",
    "1 large red pepper, deseeded and finely diced",
    "500g 5% fat beef mince",
    "1 tbsp chipotle paste",
    "1 tsp ground cumin",
    "1 tsp ground coriander",
    "200g can chopped tomatoes",
    "2 tbsp tomato purée",
    "20g coriander, stalks chopped, leaves reserved",
    "2 red onions, thinly sliced",
    "2 limes, juiced",
    "2 x 250g pouches cooked microwave wholemeal basmati rice",
    "400g can black beans, drained",
    "200g cherry tomatoes, halved",
    "198g can sweetcorn (salt- and sugar-free)",
    "2 small avocados, sliced"
],
    "Rmethodecook": ["Heat the oil in a non-stick pan and fry the pepper for 5 mins until starting to soften. Add the beef, chipotle paste and spices, and cook, stirring, to break down the meat for a few minutes. Stir in the tomatoes, tomato purée, coriander stalks, 150ml water and some seasoning, then cover. Leave to simmer for 20 mins to cook through and reduce a little. Will keep chilled for up to three days, or frozen for up to three months. Defrost thoroughly and reheat until piping hot.",
    "Meanwhile, toss the onions in the lime juice in a bowl and set aside to pickle.",
    "When the mince is ready, warm the rice following pack instructions.",
    "Tip the cooked rice into four serving bowls, then add the beef and top each one with a quarter of the black beans, cherry tomatoes and corn, half an avocado (fan out the slices, if you like), and the coriander leaves. Spoon the pickled onions on top along with any lime juice."],
    "Rimage":"https://res.cloudinary.com/dnwi9wvci/image/upload/v1670607478/mawi/spicy-beef-taco-2cd04fc_ps0uik.jpg",
    "Rlike": 0,
    "Rdislike":0,
    "Rcategorie":"breakfast"
},

    {
    "Rname": "beef lasagne",
    "Rpeparation_time":"20 mns",
    "Rcook_time":"1h 20mns",
    "Rserves":8,
    "Ringredients":["2 tsp olive oil",
    "1 brown onion, halved, finely chopped",
    "2 garlic cloves, crushed",
    "750g Coles beef mince regular",
    "2 x 400g cans Italian diced tomatoes",
    "125ml (1/2 cup) dry red wine",
    "55g (1/4 cup) tomato paste",
    "Salt & freshly ground black pepper",
    "Olive oil, extra, to grease",
    "4 fresh lasagne sheets",
    "55g (1/2 cup) coarsely grated Devondale Mozzarella Cheese Block (500g)",
    "Mixed salad leaves, to serve",
    "1L (4 cups) milk",
    "1 brown onion, halved, coarsely chopped",
    "8 fresh parsley stalks",
    "8 whole black peppercorns",
    "4 whole cloves",
    "2 bay leaves",
    "60g butter",
    "50g (1/3 cup) plain flour",
    "70g (1 cup) finely grated parmesan",
    "Pinch ground nutmeg",
    "Salt & ground white pepper"
    ],
    "Rmethodecook": ["Heat the oil in a large frying pan over medium heat. Add the onion and garlic and cook, stirring, for 5 minutes or until onion softens. Add the mince and cook, stirring with a wooden spoon to break up any lumps, for 5 minutes or until mince changes colour. Add the tomato, wine and tomato paste, and bring to the boil. Reduce heat to low. Simmer, uncovered, stirring occasionally, for 30 minutes or until sauce thickens slightly. Remove from heat. Taste and season with salt and pepper.",
    "Meanwhile, to make the cheese sauce, combine the milk, onion, parsley stalks, peppercorns, cloves and bay leaves in a medium saucepan and bring to a simmer over medium heat. Remove from heat and set aside for 15 minutes to infuse.",
    "Strain the milk mixture through a fine sieve into a large jug. Discard solids.",
    "Melt the butter in a large saucepan over medium-high heat until foaming. Add the flour and cook, stirring, for 1-2 minutes or until mixture bubbles and begins to come away from the side of the pan. Remove from heat.",
    "Gradually pour in half the milk, whisking constantly with a balloon whisk, until mixture is smooth. Gradually add the remaining milk, whisking until smooth and combined.",
    "Place saucepan over medium-high heat and bring to the boil, stirring constantly with a wooden spoon, for 5 minutes or until sauce thickens and coats the back of the spoon. Remove from heat. Add the parmesan and stir until cheese melts. Taste and season with nutmeg, salt and white pepper.",
    "Preheat oven to 180°C. Brush a rectangular 3L (12 cup) capacity ovenproof dish with oil to lightly grease. Spread one-quarter of the bechamel sauce over the base of the prepared dish. Arrange 1 lasagne sheet over the sauce. Top with one-third of the mince mixture and one-third of the remaining bechamel sauce. Continue layering with the remaining lasagne sheets, mince mixture and bechamel, finishing with a layer of bechamel. Sprinkle with mozzarella. Place on a baking tray. Bake in preheated oven for 40 minutes or until cheese melts, is golden brown, and the edges are bubbling. Remove from oven and set aside for 10 minutes to set.",
    "Cut the lasagne into 8 portions and serve with mixed salad leaves."],
    "Rimage":"https://res.cloudinary.com/dnwi9wvci/image/upload/v1670608141/mawi/our-favourite-lasagne-118950-2_bzorsp.jpg",
    "Rlike": 0,
    "Rdislike":0,
    "Rcategorie":"dinner"
},

    {
    "Rname": "versatile Zucchini fritters",
    "Rpeparation_time":"20 mns",
    "Rcook_time":"10 mns",
    "Rserves":3,
    "Ringredients":["3 (about 400g) medium zucchini",
    "75g (1/2 cup) self-raising flour",
    "40g (1/2 cup) parmesan, finely grated, plus extra to serve",
    "3 shallots, ends trimmed, thinly sliced",
    "1 egg, whisked",
    "1/4 cup fresh continental parsley, chopped",
    "2 tsp dried oregano leaves",
    "1/4 tsp ground nutmeg",
    "1 tsp salt",
    "1 tbsp olive oil"],
    "Rmethodecook": ["Trim the ends from zucchini. Coarsely grate the zucchini. Place in a colander and squeeze out as much excess moisture as possible. Transfer to a bowl. Stir in self-raising flour, parmesan, shallots, egg, parsley, oregano, salt and nutmeg.",
    "Heat 1 teaspoon olive oil in a non-stick frying pan over medium-high heat. Drop three portions of zucchini mixture into pan. Cook for 1 1/2 minutes each side or until golden and cooked through. Transfer to a plate. Repeat with remaining olive oil and remaining zucchini mixture."],
    "Rimage":"https://res.cloudinary.com/dnwi9wvci/image/upload/v1670608450/mawi/zucchini-fritters-76488-1_lqflss.jpg",
    "Rlike": 0,
    "Rdislike":0,
    "Rcategorie":"dinner"
}

   
]